language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
  - "10"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@latest; fi
after_success:
  - npm run coverage
  - npm run test:flags
  - npm run test:docs
  - bash <(curl -s https://codecov.io/bash)
sudo: false
